version: '3.7'

volumes:
    food-flex-data:

services:
    food-flex:
        container_name: 'food-flex'
        build: .
        env_file: .env
        image: chasbob/food-flex
        volumes:
            - food-flex-data:/data
